allowBuilds:
  cpu-features: false
  esbuild: true
  protobufjs: false
  ssh2: false
minimumReleaseAgeExclude:
  - '@vercel/agent-eval@0.14.2'
patchedDependencies:
  '@vercel/agent-eval@0.14.2': patches/@vercel__agent-eval@0.14.2.patch
